#%RAML 1.0 ResourceType
usage: This resourceType should be used for any collection of items
get:
  displayName: List<<resourcePathName | !uppercamelcase>>
  description: List all <<resourcePathName>>
  responses:
    200:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>[]
post:
  displayName: Create<<resourcePathName | !singularize | !uppercamelcase>>
  description: Create a new <<resourcePathName | !singularize>>
  body:
    type: <<resourcePathName | !singularize | !uppercamelcase>>Create
  responses:
    201:
      description: <<resourcePathName | !singularize>> created
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>
    409:
      description: conflict, a <<resourcePathName | !singularize>> with this id already exists
